apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
  namespace: ecommerce
  labels:
    app: payment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-api
  template:
    metadata:
      labels:
        app: payment-api
    spec:
      containers:
        - name: payment-api
          image: ghcr.io/enesmemduhoglu/event-driven-ecommerce/payment-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: shared-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: ConnectionStrings__PaymentDb
              value: Host=postgres;Port=5432;Database=payment_db;Username=postgres;Password=$(POSTGRES_PASSWORD)
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 12
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: payment-api
  namespace: ecommerce
spec:
  selector:
    app: payment-api
  ports:
    - port: 8080
      targetPort: 8080
